config/routes.rb
ALiCCSapp::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  devise_for :users
  resources :journal

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'

  match '/journal/:id(:format)', to: 'journal#show', via: 'get'

end

app/models/chemo_therapy.rb
class ChemoTherapy < ActiveRecord::Base
  attr_accessible :bodysurface, :height, :measurementdata, :recordid, :weight, :yearnumber
end

app/models/chronic_disease.rb
class ChronicDisease < ActiveRecord::Base
  attr_accessible :text

  def chronicdisease_combo
    "#{seq} - #{self.text}"
  end
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :countrycode, :countryname
  def country_combo
    "#{id} - #{self.countryname}"
  end
end

app/models/cytostatic_drug.rb
class CytostaticDrug < ActiveRecord::Base
  attr_accessible :text
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  attr_accessible :text
end

app/models/dose_quality.rb
class DoseQuality < ActiveRecord::Base
  attr_accessible :text
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  attr_accessible :gendername

  def gender_combo
    "#{id} - #{self.gendername}"
  end
end

app/models/institute.rb
class Institute < ActiveRecord::Base
  attr_accessible :address, :name
end

app/models/laterality_rlbn.rb
class LateralityRlbn < ActiveRecord::Base
  attr_accessible :text
end

app/models/laterality_rlbu.rb
class LateralityRlbu < ActiveRecord::Base
  attr_accessible :text
end

app/models/missing_info.rb
class MissingInfo < ActiveRecord::Base
  attr_accessible :text, :textshort

  def missingInfo_combo
    "#{seq} - #{self.text}"
  end
end

app/models/no_yes.rb
class NoYes < ActiveRecord::Base
  attr_accessible :text
  def noyes_combo
    "#{seq} - #{self.text}"
  end
end

app/models/no_yes_unknown.rb
class NoYesUnknown < ActiveRecord::Base
  attr_accessible :text
  def noyesunknown_combo
    "#{seq} - #{self.text}"
  end
end

app/models/source.rb
class Source < ActiveRecord::Base
  attr_accessible :text
end

app/models/surgery.rb
class Surgery < ActiveRecord::Base
  attr_accessible :studynumber, :surgerycompleteremovalorgan, :surgerycompleteremovalorganlaterality, :surgerycompleteremovalorganspec, :surgerydate, :surgeryradicality, :surgerytype
end

app/models/surgery_type.rb
class SurgeryType < ActiveRecord::Base
  attr_accessible :text
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/journal_helper.rb
module JournalHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">ALiCCS App</a>
    by Hörður and Þórunn
  </small>
  <!--<nav>
    <ul>
      <li><%= link_to "About",   'about_path' %></li>
      <li><%= link_to "Contact", 'contact_path' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>-->
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "ALiCCS", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <!--<li><%= link_to "Home", root_path %></li>-->
          <!--<li><%= link_to "Help", help_path %></li>-->
          <% if signed_in? %>
            
            <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
            
          <% else %>
            <!--<li><%= link_to "Sign in", signin_path %></li>-->
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", 
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <% if signed_in? %>
      <%= render 'layouts/header' %>
    <% end %>
      <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>

      <%= render 'layouts/footer' %>
      <!--<%= debug(params) if Rails.env.development? %>-->
    </div>
  </body>
</html>